### ISSUE TITLE
third pane for agent instrumentation missing in version 1.8.2 gui

### ISSUE THREAD

**Issue by alexpmorris** [exense/djigger#103]
I'm not sure if I'm just missing how it's being done in the latest version, but I tried running version 1.4.2 of djigger that's featured in the videos and the agent instrumentation panel shows right up.  However, with the latest version of djigger (v1.8.2) no matter what I try and can't seem to bring up that panel.  Would appreciate any additional insight you can offer into how this might have changed since the older version.  

Besides that, many thanks to you and your team for releasing this terrific profiling tool-set.

**Comment by jeromecomte** [comment]
Hi Alexander,

Thanks a lot for your feedback.
The "instrumentation panel" of the TreeView has been replaced by the
Event-Tab in the 1.8.2. In the Event-Tab you should find a list of all
instrumentation events you're subscribing to (Tab Subscriptions).

Cheers,
Jérôme

2018-05-13 20:40 GMT+02:00 Alexander Morris <notifications@github.com>:

**Comment by alexpmorris** [comment]
Still seems I'm doing something wrong.  In 1.8.2, I see it connect to the JVM in agent mode, but nothing really ever shows up on the Events tab (though it does on the Subscriptions tab).  In version 1.4.2, I see the instrumentation on pane 3, and I also see it added in the JVM, along with statements such as "Sent dumps in: 103" *(which I did not see with version 1.8.2)*.  Despite all this, however, all the numbers still seem stuck at zero.  For reference, the JVM version is 1.8.0_121.  

Appreciate any thoughts you may have on what I'm still missing here.  Thanks!

![image](https://user-images.githubusercontent.com/5326789/40150974-f79bf700-594a-11e8-8e67-23dda64a26e4.png)

**Comment by david-stephan** [comment]
Hi Alexander, 
I know it's a pretty old issue, but I did a quick check and could not reproduce the issue on the latest 1.11.1 version.
Example, instrument a method from the Thread Tree View:
![image](https://user-images.githubusercontent.com/19704350/104461425-9b6a3a00-55af-11eb-9d6d-1d821532c437.png)
The method show up in the list of suscription: 
![image](https://user-images.githubusercontent.com/19704350/104461506-b63cae80-55af-11eb-849c-2631c1cb622c.png)
the events are captured and displayed on the event tab (make sure the pseudo events are diabled to show only your events):
![image](https://user-images.githubusercontent.com/19704350/104461697-f69c2c80-55af-11eb-88b1-5ac9dbf5d90d.png)

Note: above example is for a direct connection between djigger client and the agent, the same was also working fine for me using the djigger collector (persistent monitoring).

Let me know if that's of any help.
Regards,
David

**Comment by david-stephan** [comment]
Hi there! We provided a solution to the mentioned issue but haven't heard back in a while. We'll go ahead and close this ticket for now. If you still need help or if the issue isn't resolved with the latest version, feel free to reopen it or create a new one. Thanks
