### ISSUE TITLE
[Client] Enhance ease of use (readability) - low prio

### ISSUE THREAD

**Issue by doriancransac** [exense/djigger#45]
Differentiate 0's coming from a <0 response time of an instrumented method (print "**<**0" if possible), from the initial value of a method that hasn't beeen called yet (use "-") instead.

![image](https://cloud.githubusercontent.com/assets/5418782/14579136/bcf6f5fe-039e-11e6-865b-5c81d9128443.png)

**Comment by david-stephan** [comment]
This view has been removed. Plan is to rebuild a brand new UI. Closing this issue.
