### ISSUE TITLE
Link app jar files and hook a decompiler to the client

### ISSUE THREAD

**Issue by doriancransac** [exense/djigger#64]
Allow the user to provide a path to the binaries of the application running on the monitored JVM and invoke a decompiler such as jdgui (works very well and is GPL v3) to allow integrated and on-the-fly contextual method decompilation (right-click -> decompile).

Presenting an actual jdgui window with all of the search and navigation features and the corresponding jar file, with a default pointer on the decompiled node would probably be optimal.

https://github.com/java-decompiler/jd-gui

**Comment by david-stephan** [comment]
Decompiler implemented in version 1.10.0. The decompiler is available for direct agent connection and get the jars/classes directly from the instrumented application
