### ISSUE TITLE
Make JMX-Metrics configurable

### ISSUE THREAD

**Issue by helsanaSrt** [exense/djigger#94]
We would wish to add more Memory/GC-Metrics as well as some Application specific metrics. It would be nice to have then configurable in configuration file. 
We do have different types of application JVM with different JMX Metrics. In order to keep the configuration simple but flexible it would help to have multiple configuration sets that could be applyed to an 'Connection' configuration.

**Comment by rubij** [comment]
Hi @helsanaSrt 

It is now possible in release 1.8.0 (https://github.com/denkbar/djigger/releases/tag/v1.8.0) to configure specific metrics. You can find some examples under djigger-1.8.0\conf\examples folder in the "Connections_Agent.json" and "Connections.JStack.json" configuration files.

Regarding the configuration flexibility, we will open a Github issue about it and see if our development pipeline matches this request.

Thanks for your comment.

**Comment by rubij** [comment]
@helsanaSrt  here the issue based upon your request : https://github.com/denkbar/djigger/issues/95

**Comment by jeromecomte** [comment]
Implemented in 1.8.0. Closing
