### ISSUE TITLE
Add multiple configurations set to one "Connection" configuration file

### ISSUE THREAD

**Issue by rubij** [exense/djigger#95]
As per https://github.com/denkbar/djigger/issues/94, it would be nice to have the ability to have multiple configuration sets that could be applicable to only one "Connection" configuration.

**Comment by david-stephan** [comment]
Implemented in release 1.10.2. Set of subscriptions can be defined in individual files and then assigned to connections with the property subscriptionFiles. (Example can be found in collector/src/test/conf/Connections.json )
